services:
  sqlserver2022:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sqlserver2022
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: "Kamalesh@2002"
    ports:
      - "1433:1433"
    networks:
      - siron-kyc-network

  keycloak:
    image: quay.io/keycloak/keycloak:latest
    command:
      - start-dev
    environment:
      KC_BOOTSTRAP_ADMIN_USERNAME: admin
      KC_BOOTSTRAP_ADMIN_PASSWORD: admin
      KC_HOSTNAME: http://localhost:8080
      KC_HOSTNAME_BACKCHANNEL_DYNAMIC: true
    ports:
      - "8080:8080"
    networks:
      - siron-kyc-network

  quarkus:
    build:
      dockerfile: src/main/docker/Dockerfile.jvm
    container_name: sironkyc-quarkus-app
    depends_on:
      - keycloak
      - sqlserver2022
    ports:
      - "9095:9095"
    networks:
      - siron-kyc-network
networks:
  siron-kyc-network:
    driver: bridge